source 'https://rubygems.org'

gem 'rails', '4.1.5'
gem 'sqlite3'
gem 'pg'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder'
gem 'spring', group: :development
gem 'bcrypt'
gem 'inherited_resources'
gem 'slim-rails'
gem 'simple_form'
gem 'pismo'
gem 'podcastinator'
gem 'taglib-ruby', require: 'taglib'
gem 'fog'
gem 'quiet_assets', group: :development
gem 'puma'
gem 'dotenv'
gem 'delayed_job_active_record'
gem 'whenever'
gem 'daemons'
gem 'ethon'
gem 'typhoeus'
gem 'instapaper'
gem 'foreman'
gem 'net-ssh'
gem 'net-ssh-gateway'
gem 'delayed_job-ssh_remote_worker'
